baseURL = "/"
theme = "hugo-amp"
enableRobotsTXT = true
disableHugoGeneratorInject = true
uglyURLs = false

[taxonomies]
tag = ""
group = ""
category = ""

[params]
personName = "Daniel Hannih"
alternatePageName = "Daniel Hannih, Creator and Maker"
profileImage = "https://danielhannih.com/images/daniel-hannih-avatar.jpg"
googleverification = "FKrF6yyaT3BrppQ7yi9VZtQHGzJmEWAhWv_unWkHKz8"
googleAnalytics = "UA-xxxxxxxx-x"
