version: '3.3'

services:
  hugo:
    build:
      context: ./
    entrypoint: hugo --minify --config ./config-release.toml
    volumes:
      - .:/src

  server:
    build:
      context: ./
    command: hugo server --noHTTPCache --bind 0.0.0.0 --disableLiveReload --disableFastRender
    ports:
      - "1313:1313"
    volumes:
      - .:/src
